import { Link } from "wouter";
import { Sparkles, Bot, FileText, Shield, AlertTriangle, ExternalLink, Mail } from "lucide-react";

export default function AITransparency() {
  return (
    <div className="max-w-4xl mx-auto" data-testid="page-ai-transparency">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center">
            <Sparkles className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="text-4xl font-bold" data-testid="heading-ai-transparency">AI Transparency Notice</h1>
            <p className="text-muted-foreground text-sm mt-1">Last Updated: December 8, 2025</p>
          </div>
        </div>
        <p className="text-muted-foreground">
          TypeMasterAI is committed to transparency about our use of artificial intelligence. This page explains how we use AI technology, what data is processed, and your rights regarding AI-powered features.
        </p>
      </div>

      <div className="space-y-8 prose prose-invert max-w-none">
        <section className="bg-primary/5 p-6 rounded-lg border border-primary/20">
          <div className="flex items-start gap-3">
            <Bot className="w-6 h-6 text-primary mt-1 flex-shrink-0" />
            <div>
              <h2 className="text-xl font-bold text-foreground mb-2">AI Systems We Use</h2>
              <p className="text-muted-foreground">
                TypeMasterAI integrates OpenAI's GPT-4 and GPT-4o models to power various features. When you interact with AI features on our platform, you are communicating with an automated artificial intelligence system, not a human.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">1. AI-Powered Features</h2>
          <p className="text-muted-foreground mb-4">
            The following features on TypeMasterAI use artificial intelligence:
          </p>
          <div className="grid md:grid-cols-2 gap-4">
            <div className="bg-card/30 p-4 rounded-lg border border-border">
              <h3 className="font-semibold text-foreground mb-2 flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                AI Chat Assistant
              </h3>
              <p className="text-sm text-muted-foreground">
                Our AI typing coach provides personalized tips, answers questions about typing improvement, and offers guidance. Responses are generated by GPT-4o.
              </p>
            </div>
            <div className="bg-card/30 p-4 rounded-lg border border-border">
              <h3 className="font-semibold text-foreground mb-2 flex items-center gap-2">
                <FileText className="w-4 h-4 text-primary" />
                Paragraph Generation
              </h3>
              <p className="text-sm text-muted-foreground">
                Typing test paragraphs are dynamically generated using GPT-4o-mini to ensure fresh, contextually relevant content in 23+ languages.
              </p>
            </div>
            <div className="bg-card/30 p-4 rounded-lg border border-border">
              <h3 className="font-semibold text-foreground mb-2 flex items-center gap-2">
                <FileText className="w-4 h-4 text-primary" />
                Code Snippet Generation
              </h3>
              <p className="text-sm text-muted-foreground">
                Code typing mode generates programming code snippets across multiple languages using GPT-4o-mini for realistic coding practice.
              </p>
            </div>
            <div className="bg-card/30 p-4 rounded-lg border border-border">
              <h3 className="font-semibold text-foreground mb-2 flex items-center gap-2">
                <Bot className="w-4 h-4 text-primary" />
                AI Ghost Racers
              </h3>
              <p className="text-sm text-muted-foreground">
                In multiplayer races, AI bots with generated usernames may join to ensure engaging competitions even when fewer human players are available.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">2. How AI Processes Your Data</h2>
          <p className="text-muted-foreground mb-4">
            When you use AI features, the following data may be sent to OpenAI's servers for processing:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li><strong className="text-foreground">AI Chat:</strong> Your messages and conversation history within the current session</li>
            <li><strong className="text-foreground">Paragraph Generation:</strong> Selected language, category preferences, and difficulty settings</li>
            <li><strong className="text-foreground">Code Generation:</strong> Selected programming language and complexity level</li>
            <li><strong className="text-foreground">Web Search:</strong> When enabled, your queries may be used to search the internet for current information</li>
          </ul>
          <p className="text-muted-foreground mt-4">
            <strong className="text-foreground">Important:</strong> We do not send your personal account information, typing test results, or analytics data to AI providers unless you explicitly include it in your chat messages.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">3. Data Retention by AI Providers</h2>
          <p className="text-muted-foreground mb-4">
            OpenAI's data handling practices:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>API data is retained for up to 30 days for abuse monitoring, then deleted</li>
            <li>OpenAI does <strong className="text-foreground">not</strong> use API data to train their models without explicit consent</li>
            <li>Data is processed in the United States and other countries where OpenAI operates</li>
          </ul>
          <p className="text-muted-foreground mt-4">
            For complete details, see{" "}
            <a 
              href="https://openai.com/policies/privacy-policy" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:underline inline-flex items-center gap-1"
            >
              OpenAI's Privacy Policy
              <ExternalLink className="w-3 h-3" />
            </a>{" "}
            and{" "}
            <a 
              href="https://openai.com/policies/api-data-usage-policies" 
              target="_blank" 
              rel="noopener noreferrer"
              className="text-primary hover:underline inline-flex items-center gap-1"
            >
              API Data Usage Policies
              <ExternalLink className="w-3 h-3" />
            </a>.
          </p>
        </section>

        <section className="bg-amber-500/10 p-6 rounded-lg border border-amber-500/20">
          <div className="flex items-start gap-3">
            <AlertTriangle className="w-6 h-6 text-amber-500 mt-1 flex-shrink-0" />
            <div>
              <h2 className="text-xl font-bold text-foreground mb-2">4. AI Limitations & Accuracy</h2>
              <p className="text-muted-foreground mb-4">
                Please be aware of the following limitations:
              </p>
              <ul className="list-disc pl-6 text-muted-foreground space-y-2">
                <li>AI-generated content may contain <strong className="text-foreground">factual errors or inaccuracies</strong></li>
                <li>AI responses are generated in real-time and may vary in quality</li>
                <li>AI cannot provide <strong className="text-foreground">professional advice</strong> (medical, legal, financial)</li>
                <li>Generated code snippets may contain bugs or security vulnerabilities</li>
                <li>AI chat does not have memory of previous sessions unless specifically designed</li>
              </ul>
              <p className="text-muted-foreground mt-4">
                <strong className="text-foreground">Always verify important information</strong> from reliable sources before relying on AI-generated content.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">5. Your Rights & Controls</h2>
          <p className="text-muted-foreground mb-4">
            You have the following rights regarding AI features:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li><strong className="text-foreground">Opt-Out:</strong> You can use TypeMasterAI without interacting with AI features (use pre-generated paragraphs instead)</li>
            <li><strong className="text-foreground">Data Access:</strong> Request information about data sent to AI providers</li>
            <li><strong className="text-foreground">Deletion:</strong> Request deletion of your AI conversation history</li>
            <li><strong className="text-foreground">Report Issues:</strong> Flag inappropriate or harmful AI-generated content</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">6. EU AI Act Compliance</h2>
          <p className="text-muted-foreground mb-4">
            In compliance with the European Union AI Act (Regulation (EU) 2024/1689):
          </p>
          <ul className="list-disc pl-6 text-muted-foreground space-y-2">
            <li>We clearly disclose that our chatbot is powered by artificial intelligence</li>
            <li>AI-generated content is identified where applicable</li>
            <li>We do not use prohibited AI practices (social scoring, subliminal manipulation, etc.)</li>
            <li>Our AI usage falls under "limited-risk" category requiring transparency obligations</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">7. Updates to This Notice</h2>
          <p className="text-muted-foreground">
            We may update this AI Transparency Notice as our AI features evolve or as regulations change. Significant updates will be communicated through our platform. We encourage you to review this page periodically.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-foreground mb-4">8. Related Policies</h2>
          <ul className="space-y-2">
            <li>
              <Link href="/privacy-policy" className="text-primary hover:underline">Privacy Policy</Link>
              <span className="text-muted-foreground"> - How we collect and protect your personal data</span>
            </li>
            <li>
              <Link href="/terms-of-service" className="text-primary hover:underline">Terms of Service</Link>
              <span className="text-muted-foreground"> - Rules for using TypeMasterAI</span>
            </li>
            <li>
              <Link href="/cookie-policy" className="text-primary hover:underline">Cookie Policy</Link>
              <span className="text-muted-foreground"> - How we use cookies and tracking technologies</span>
            </li>
          </ul>
        </section>

        <section className="bg-card/50 p-6 rounded-lg border border-border">
          <h2 className="text-2xl font-bold text-foreground mb-4 flex items-center gap-2">
            <Shield className="w-6 h-6 text-primary" />
            Questions About Our AI?
          </h2>
          <p className="text-muted-foreground mb-4">
            If you have questions about our use of artificial intelligence, please contact us:
          </p>
          <div className="flex items-center gap-2 text-muted-foreground">
            <Mail className="w-4 h-4 text-primary" />
            <a href="mailto:ai-transparency@typemasterai.com" className="text-primary hover:underline">
              ai-transparency@typemasterai.com
            </a>
          </div>
        </section>
      </div>
    </div>
  );
}
