import { db } from "./storage";
import { dictationSentences } from "@shared/schema";

const sentences = [
  // EASY - Simple 5-8 word sentences, common vocabulary (20 sentences)
  {
    sentence: "The cat sleeps on the warm sofa.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 32,
  },
  {
    sentence: "I like to drink coffee in the morning.",
    difficulty: "easy",
    category: "general",
    wordCount: 8,
    characterCount: 38,
  },
  {
    sentence: "She reads a good book every night.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 34,
  },
  {
    sentence: "The sun shines brightly in the sky.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 35,
  },
  {
    sentence: "He walks to school with his friends.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 36,
  },
  {
    sentence: "My dog loves playing in the park.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 33,
  },
  {
    sentence: "We watch movies together on weekends.",
    difficulty: "easy",
    category: "entertainment",
    wordCount: 6,
    characterCount: 37,
  },
  {
    sentence: "The flowers bloom beautifully in spring.",
    difficulty: "easy",
    category: "general",
    wordCount: 6,
    characterCount: 40,
  },
  {
    sentence: "I enjoy listening to music daily.",
    difficulty: "easy",
    category: "entertainment",
    wordCount: 6,
    characterCount: 33,
  },
  {
    sentence: "They play soccer after school ends.",
    difficulty: "easy",
    category: "general",
    wordCount: 6,
    characterCount: 35,
  },
  {
    sentence: "My family goes camping every summer.",
    difficulty: "easy",
    category: "general",
    wordCount: 6,
    characterCount: 36,
  },
  {
    sentence: "The bakery sells fresh bread each morning.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 42,
  },
  {
    sentence: "She teaches children at the local school.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 41,
  },
  {
    sentence: "We celebrate birthdays with cake and gifts.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 43,
  },
  {
    sentence: "The train arrives at exactly seven o'clock.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 43,
  },
  {
    sentence: "He practices piano for one hour daily.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 38,
  },
  {
    sentence: "The library offers free books to everyone.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 42,
  },
  {
    sentence: "Birds sing cheerful songs in the trees.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 39,
  },
  {
    sentence: "I write letters to my best friend.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 34,
  },
  {
    sentence: "The ocean waves crash against the shore.",
    difficulty: "easy",
    category: "general",
    wordCount: 7,
    characterCount: 40,
  },

  // MEDIUM - 10-15 word sentences, moderate complexity (25 sentences)
  {
    sentence: "Technology has transformed how we communicate with each other in our daily lives.",
    difficulty: "medium",
    category: "technology",
    wordCount: 13,
    characterCount: 81,
  },
  {
    sentence: "The library offers a quiet space for reading and studying during exam season.",
    difficulty: "medium",
    category: "general",
    wordCount: 13,
    characterCount: 77,
  },
  {
    sentence: "Regular exercise and healthy eating habits contribute significantly to overall wellness and longevity.",
    difficulty: "medium",
    category: "health",
    wordCount: 13,
    characterCount: 101,
  },
  {
    sentence: "Climate change affects weather patterns around the world in unexpected and dramatic ways.",
    difficulty: "medium",
    category: "science",
    wordCount: 14,
    characterCount: 89,
  },
  {
    sentence: "Learning a new language opens doors to different cultures and expands career opportunities globally.",
    difficulty: "medium",
    category: "education",
    wordCount: 14,
    characterCount: 100,
  },
  {
    sentence: "The museum showcases ancient artifacts that tell fascinating stories about human history and civilization.",
    difficulty: "medium",
    category: "culture",
    wordCount: 14,
    characterCount: 104,
  },
  {
    sentence: "Online shopping has revolutionized retail by providing convenience and competitive prices to consumers worldwide.",
    difficulty: "medium",
    category: "business",
    wordCount: 14,
    characterCount: 112,
  },
  {
    sentence: "Artificial intelligence is reshaping industries from healthcare to finance at an unprecedented pace.",
    difficulty: "medium",
    category: "technology",
    wordCount: 14,
    characterCount: 99,
  },
  {
    sentence: "Sustainable farming practices help preserve natural resources while ensuring food security for future generations.",
    difficulty: "medium",
    category: "environment",
    wordCount: 14,
    characterCount: 111,
  },
  {
    sentence: "Professional athletes train rigorously for years to compete at the highest levels of their sport.",
    difficulty: "medium",
    category: "sports",
    wordCount: 15,
    characterCount: 97,
  },
  {
    sentence: "Social media platforms connect billions of people but also raise concerns about privacy and mental health.",
    difficulty: "medium",
    category: "technology",
    wordCount: 16,
    characterCount: 105,
  },
  {
    sentence: "Renewable energy sources like solar and wind power are becoming increasingly cost-effective alternatives to fossil fuels.",
    difficulty: "medium",
    category: "environment",
    wordCount: 16,
    characterCount: 119,
  },
  {
    sentence: "The education system must evolve to prepare students for jobs that don't exist yet.",
    difficulty: "medium",
    category: "education",
    wordCount: 15,
    characterCount: 84,
  },
  {
    sentence: "Remote work has become the new normal for many professionals seeking better work-life balance.",
    difficulty: "medium",
    category: "business",
    wordCount: 15,
    characterCount: 94,
  },
  {
    sentence: "Space exploration continues to push the boundaries of human knowledge and technological innovation.",
    difficulty: "medium",
    category: "science",
    wordCount: 14,
    characterCount: 99,
  },
  {
    sentence: "Financial literacy education helps people make informed decisions about saving, investing, and managing debt.",
    difficulty: "medium",
    category: "business",
    wordCount: 14,
    characterCount: 107,
  },
  {
    sentence: "Urban planning shapes how cities grow and determines the quality of life for their residents.",
    difficulty: "medium",
    category: "general",
    wordCount: 16,
    characterCount: 93,
  },
  {
    sentence: "Scientific research requires patience, precision, and a willingness to accept unexpected results.",
    difficulty: "medium",
    category: "science",
    wordCount: 13,
    characterCount: 96,
  },
  {
    sentence: "Cultural diversity enriches communities by bringing together different perspectives, traditions, and creative expressions.",
    difficulty: "medium",
    category: "culture",
    wordCount: 14,
    characterCount: 119,
  },
  {
    sentence: "Digital marketing strategies help businesses reach target audiences through personalized content and data analytics.",
    difficulty: "medium",
    category: "business",
    wordCount: 14,
    characterCount: 112,
  },
  {
    sentence: "Mental health awareness campaigns reduce stigma and encourage people to seek professional help when needed.",
    difficulty: "medium",
    category: "health",
    wordCount: 15,
    characterCount: 106,
  },
  {
    sentence: "The hospitality industry focuses on creating memorable experiences that exceed customer expectations consistently.",
    difficulty: "medium",
    category: "business",
    wordCount: 13,
    characterCount: 112,
  },
  {
    sentence: "Documentary films educate viewers about important social issues and inspire positive change in communities.",
    difficulty: "medium",
    category: "entertainment",
    wordCount: 14,
    characterCount: 106,
  },
  {
    sentence: "Cybersecurity experts protect sensitive information from digital threats and unauthorized access attempts.",
    difficulty: "medium",
    category: "technology",
    wordCount: 12,
    characterCount: 102,
  },
  {
    sentence: "International trade agreements facilitate economic cooperation between nations while addressing environmental concerns.",
    difficulty: "medium",
    category: "business",
    wordCount: 12,
    characterCount: 114,
  },

  // HARD - 15-20 word sentences, complex structure (15 sentences)
  {
    sentence: "Quantum mechanics revolutionized our understanding of subatomic particle behavior and challenged classical physics principles in profound and unexpected ways.",
    difficulty: "hard",
    category: "science",
    wordCount: 21,
    characterCount: 159,
  },
  {
    sentence: "Biodiversity conservation requires international cooperation, sustainable practices, and long-term commitment from governments, organizations, and individual citizens worldwide.",
    difficulty: "hard",
    category: "environment",
    wordCount: 19,
    characterCount: 175,
  },
  {
    sentence: "Neuroscientific research continues to uncover complex mechanisms underlying human consciousness, memory formation, and the intricate neural networks that define cognitive processes.",
    difficulty: "hard",
    category: "science",
    wordCount: 22,
    characterCount: 180,
  },
  {
    sentence: "Globalization interconnects economies, cultures, and political systems across continents, creating both tremendous opportunities and significant challenges for sustainable development.",
    difficulty: "hard",
    category: "business",
    wordCount: 21,
    characterCount: 181,
  },
  {
    sentence: "Philosophical discourse examines fundamental questions about existence, morality, knowledge, and reality through rigorous logical analysis and systematic argumentation.",
    difficulty: "hard",
    category: "philosophy",
    wordCount: 20,
    characterCount: 166,
  },
  {
    sentence: "Cryptocurrency technologies leverage blockchain architecture to enable decentralized financial transactions while introducing novel regulatory challenges for traditional banking institutions.",
    difficulty: "hard",
    category: "technology",
    wordCount: 20,
    characterCount: 186,
  },
  {
    sentence: "Epidemiological studies analyze disease patterns across populations to identify risk factors, develop prevention strategies, and inform public health policy decisions.",
    difficulty: "hard",
    category: "health",
    wordCount: 22,
    characterCount: 167,
  },
  {
    sentence: "Postmodern architecture deliberately rejects minimalist aesthetics in favor of playful ornamentation, historical references, and eclectic combinations of diverse stylistic elements.",
    difficulty: "hard",
    category: "culture",
    wordCount: 22,
    characterCount: 180,
  },
  {
    sentence: "Machine learning algorithms process vast datasets to identify patterns, make predictions, and continuously improve performance through iterative training cycles and feedback mechanisms.",
    difficulty: "hard",
    category: "technology",
    wordCount: 24,
    characterCount: 185,
  },
  {
    sentence: "Constitutional law establishes fundamental principles governing state authority, individual rights, and the delicate balance between democratic governance and judicial oversight.",
    difficulty: "hard",
    category: "law",
    wordCount: 22,
    characterCount: 176,
  },
  {
    sentence: "Astrophysics explores cosmic phenomena ranging from stellar evolution to gravitational waves, expanding our comprehension of the universe's origins and ultimate fate.",
    difficulty: "hard",
    category: "science",
    wordCount: 23,
    characterCount: 163,
  },
  {
    sentence: "Sustainable development balances economic growth with environmental protection and social equity, requiring innovative solutions to address interconnected global challenges.",
    difficulty: "hard",
    category: "environment",
    wordCount: 21,
    characterCount: 172,
  },
  {
    sentence: "Comparative literature examines texts across linguistic and cultural boundaries, revealing universal themes while celebrating the distinctive characteristics of diverse literary traditions.",
    difficulty: "hard",
    category: "culture",
    wordCount: 23,
    characterCount: 186,
  },
  {
    sentence: "Immunology investigates the sophisticated defense mechanisms protecting organisms from pathogens, autoimmune disorders, and malignant cells through coordinated cellular and molecular responses.",
    difficulty: "hard",
    category: "science",
    wordCount: 23,
    characterCount: 193,
  },
  {
    sentence: "Geopolitical tensions arise from competing national interests, resource scarcity, and ideological differences, necessitating diplomatic negotiation and multilateral cooperation frameworks.",
    difficulty: "hard",
    category: "politics",
    wordCount: 21,
    characterCount: 185,
  },
];

export async function seedDictationSentences() {
  console.log("Seeding dictation sentences...");
  
  try {
    for (const sentence of sentences) {
      await db.insert(dictationSentences).values(sentence).onConflictDoNothing();
    }
    
    console.log(`✓ Successfully seeded ${sentences.length} dictation sentences`);
  } catch (error) {
    console.error("Error seeding dictation sentences:", error);
    throw error;
  }
}
